# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f350e0ac460f87f8e0acf2049e512c9a436510f716210dde76c806aad9e110a761148d4e23aa585ad4b8efcf3dfb6c9632f19197b0cd74f9347a2e92544649f

test:
  secret_key_base: 29b46c35e4bfe72eccfc6efad3e7e9039c97633ef17413327650de15fc9e1073e1af9b60a3d8f628f065baf42957b36876bd58ae50954ab886cfd34bd6a4a888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
